### ISSUE TITLE
Deep press non 3d touch devices.

### ISSUE THREAD

**Issue by jimz011** [roflcoopter/deep-press#1]
When using deep_press on non 3d touch devices it will hang/bug very often. Any way to disable this for non-3d touch devices without the need of duplicating code?

**Comment by roflcoopter** [comment]
When you say non-3d touch do you mean like an android phone or a PC? Or both?

**Comment by jimz011** [comment]
I also mean my older iPad Air. But yeah mostly Android users seem to have problems with it. I do not use an Android device so I can’t test it for you. However many people have downloaded my config and the Android users of them say it does not work.

**Comment by roflcoopter** [comment]
This is fixed in the latest [release](https://github.com/roflcoopter/deep-press/releases/tag/1.2.0). ```deep-press``` is now disabled by default on unsupported devices, but can be turned on if one desires
