### ISSUE TITLE
Using deep-press will immediately activate the button that gets popped up.

### ISSUE THREAD

**Issue by jimz011** [roflcoopter/deep-press#2]
When using deep-press on light button that opens a popup card, it will immediately do another tap_action on that location. In my example I have a light with color wheel. I use deep-press to issue the popup. The popup shows up with the color wheel. The location where I initially used the deep_press function will be tapped again after activation. In my example my finger will be somewhere on the color wheel (depending on where the original button is pressed) and it will immediately choose that color. In my case I have LEDs that always turn blue when I deep press that button (as that color is in that exact spot.)

**Comment by roflcoopter** [comment]
Yeah that is annoying, I'll have a go at it

**Comment by roflcoopter** [comment]
This should be solved by [1.1.0.b1](https://github.com/roflcoopter/deep-press/releases/tag/1.1.0.b1).
Seems to work fine for me, can you confirm?

**Comment by jimz011** [comment]
It seems to work fine now. I thank you very very much (and also all the users that installed my lovelace config are thanking you!
