### ISSUE TITLE
Cannot slip left and right on the button card with the compact-custom-header

### ISSUE THREAD

**Issue by horacecar** [roflcoopter/deep-press#4]
Cannot slip left and right on the (Button Card by RomRider) with the compact-custom-header

HA: 0.100.2, IPHONE XS MAX IOS:13.0

Hello, roflcoopter,thanks for the update.... one of your very old version can slip to left page and right page on the button card with the compact-custom-header , the latest version cannot , but after maybe version 1.1? It become cannot . i will upload the old version to you, but i dont remember what is the version number lol.

[deep-press.zip](https://github.com/roflcoopter/deep-press/files/3757168/deep-press.zip)

`

`

**Comment by roflcoopter** [comment]
Resolved in the latest beta [1.2.3b5](https://github.com/roflcoopter/deep-press/releases/tag/1.2.3b5)
