### ISSUE TITLE
Buttons don't work anymore

### ISSUE THREAD

**Issue by sanderabbink** [roflcoopter/deep-press#5]
Just installed deep-press, placed this in the resourses. But when I click on a button I see this error in my console.

<img width="830" alt="error" src="https://user-images.githubusercontent.com/19343007/72151082-8dd01200-33a7-11ea-9308-7f7c41def255.png">

**Comment by roflcoopter** [comment]
Sorry completely missed this issue being added!

Whats the card you have deep-press applied to? Lovelace stock button?

**Comment by roflcoopter** [comment]
Closing as no information was provided.
If you are still experiencing this issue i suggest you try out the latest version which includes lots of improvements.
