### ISSUE TITLE
Deep press blocks popups (browser_mod 1.3.0)

### ISSUE THREAD

**Issue by ASNNetworks** [roflcoopter/deep-press#7]
Hi,

So I found out (after 3 hours of pulling out my hair thinking I was going crazy lol) that Deep press and the new browser_mod 1.3.0 update don't play along nice. With browser_mod 1.3.0 the format of envoking popup has changed. It now uses `fire-dom-action`. I don't know if this is related and Deep press needs to be updatet to fully utilize this. But it does seem something is now broken. 

Using hold_action on RomRider's button card, while using the new `fire-dom-action` (RomRider's card now suppports that) I don't get a popup, deep_press itself does work. Using other methods, like global popup and more-info dialogues popups do show when hold_action is used (and also deep_press works). 

I cleared all browsers and caches a lot of times and restarted all devices an HA server multiple times. I noticed that all devices, except iOS still had this issue. So I thought, let's disable deep_press since that is not used on my other devices. And bam: all works when removed deep_press. Installing it again, breaks popups again on buttons that use `fire-dom-action`. 

This issue happened when I installed browser_mod 1.3.0 and used the new format, so something between browser_mod and deep_press seem to not play nice. I'm sad to have to remove deep_press since popups are a must for my UI. I hope this is fixable.

**Comment by roflcoopter** [comment]
This should be fixed in the latest release, [2.1.3](https://github.com/roflcoopter/deep-press/releases/tag/2.1.3).
Let me know if you run into any issues.
